name: Packaging
 
on:
  - push
 
jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - uses: actions/setup-python@v4.0.0
        with:
            python-version: "3.10"
 
      - name: Install tox
        run: python -m pip install tox
 
      - name: Run black
        run: tox -e format

  lint:
    name: Check lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - uses: actions/setup-python@v4.0.0
        with:
            python-version: "3.10"
 
      - name: Install tox
        run: python -m pip install tox
 
      - name: Run black
        run: tox -e ruff_lint

  type-checking:
    name: Check type-checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - uses: actions/setup-python@v4.0.0
        with:
            python-version: "3.10"
 
      - name: Install tox
        run: python -m pip install tox
 
      - name: Run black
        run: tox -e typecheck
