name: Packaging
 
on:
  - push
 
jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - uses: actions/setup-python@v4.0.0
        with:
            python-version: "3.10"
 
      - name: Install tox
        run: python -m pip install tox
 
      - name: Run black
        run: tox -e format

  lint:
    name: Check lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - uses: actions/setup-python@v4.0.0
        with:
            python-version: "3.10"
 
      - name: Install tox
        run: python -m pip install tox
 
      - name: Run black
        run: tox -e ruff_lint

  type-checking:
    name: Check type-checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - uses: actions/setup-python@v4.0.0
        with:
            python-version: "3.10"
 
      - name: Install tox
        run: python -m pip install tox
 
      - name: Run black
        run: tox -e typecheck
 
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - version: "3.10"
            toxenv: "py310"
          - version: "3.11"
            toxenv: "py311"
 
    steps:
      - uses: actions/checkout@v3
 
      - uses: actions/setup-python@v4.0.0
        with:
          python-version: ${{ matrix.python.version }}
 
      - name: Install tox
        run: python -m pip install tox
 
      - name: Run pytest
        run: tox -e ${{ matrix.python.toxenv }}
